using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BackendIntegrador.Infrastructure.Migrations
{
    public partial class FixTrabajadorIdAutoIncrement : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Trabajadores" ALTER COLUMN "TrabajadorId" ADD GENERATED BY DEFAULT AS IDENTITY;
            """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Trabajadores" ALTER COLUMN "TrabajadorId" DROP IDENTITY;
            """);
        }
    }
}
