// <auto-generated />
using System;
using BackendIntegrador.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendIntegrador.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AlertaGemelo", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertaId"));

                    b.Property<DateTime>("CreadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeidaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Recomendacion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("AlertaId");

                    b.HasIndex("ExpiraUtc");

                    b.HasIndex("FincaId", "Leida", "CreadaUtc");

                    b.ToTable("AlertasGemelo");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.Property<int>("AnalisisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalisisId"));

                    b.Property<DateTime>("FechaHoraAnalisis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MuestraId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("AnalisisId");

                    b.HasIndex("MuestraId");

                    b.ToTable("AnalisisCalidad");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.Property<int>("CentroAcopioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentroAcopioId"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CentroAcopioId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("CentrosAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.Property<int>("FincaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FincaId"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProductorId")
                        .HasColumnType("integer");

                    b.HasKey("FincaId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ProductorId");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.FincaGemeloEstado", b =>
                {
                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FuenteClima")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ScoreRiesgoGlobal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("VersionMotor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("FincaId");

                    b.ToTable("FincasGemeloEstado");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.LecturaClimatica", b =>
                {
                    b.Property<int>("LecturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LecturaId"));

                    b.Property<int>("DiasConsecutivosCalor")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("HumedadMedia")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("PrecipitacionMm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TempMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TempMedia")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TempMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("ThiMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("LecturaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("FincaId", "Fecha")
                        .IsUnique();

                    b.ToTable("LecturasClimaticas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CentroAcopioId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TransporteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VolumenCapturadoLitros")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("LoteId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("OrdenoId");

                    b.HasIndex("TransporteId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.Property<int>("MuestraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MuestraId"));

                    b.Property<DateTime>("FechaHoraToma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int>("TecnicoPorUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("MuestraId");

                    b.HasIndex("LoteId");

                    b.HasIndex("TecnicoPorUsuarioId");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MunicipioId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("MunicipioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.Property<int>("OrdenoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenoId"));

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VolumenLitros")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("OrdenoId");

                    b.HasIndex("FincaId");

                    b.ToTable("Ordenos");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ParametroCalidad", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParametroId"));

                    b.Property<int?>("CentroAcopioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("ParametroId");

                    b.HasIndex("CentroAcopioId", "Nombre")
                        .IsUnique();

                    b.ToTable("ParametrosCalidad");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.PrediccionGemelo", b =>
                {
                    b.Property<int>("PrediccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrediccionId"));

                    b.Property<decimal>("Confianza")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("text");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneradaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorizonteDias")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPrediccion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PrediccionId");

                    b.HasIndex("GeneradaUtc");

                    b.HasIndex("FincaId", "TipoPrediccion", "HorizonteDias");

                    b.ToTable("PrediccionesGemelo");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.Property<int>("ProductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductorId"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ProductorId");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Productores");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.RecepcionAcopio", b =>
                {
                    b.Property<int>("RecepcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecepcionId"));

                    b.Property<int>("CentroAcopioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TemperaturaRecepcion")
                        .HasColumnType("integer");

                    b.Property<int>("TransporteId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VolumenLitrosRecibidos")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("RecepcionId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("TransporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecepcionesAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ResultadoParametro", b =>
                {
                    b.Property<int>("AnalisisId")
                        .HasColumnType("integer");

                    b.Property<int>("ParametroId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorResultado")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("AnalisisId", "ParametroId");

                    b.HasIndex("ParametroId");

                    b.ToTable("ResultadosParametro");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TipoDocumentoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Trabajador", b =>
                {
                    b.Property<int>("TrabajadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrabajadorId");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransporteId"));

                    b.Property<DateTime?>("FechaHoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TemperaturaInicio")
                        .HasColumnType("integer");

                    b.HasKey("TransporteId");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<int?>("CentroAcopioId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AlertaGemelo", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithMany("AlertasGemelo")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Muestra", "Muestra")
                        .WithMany("Analisis")
                        .HasForeignKey("MuestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Municipio", "Municipio")
                        .WithMany("CentrosAcopio")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Fincas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Productor", "Productor")
                        .WithMany("Fincas")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("Productor");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.FincaGemeloEstado", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithOne("GemeloEstado")
                        .HasForeignKey("BackendIntegrador.Domain.Entities.FincaGemeloEstado", "FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.LecturaClimatica", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithMany("LecturasClimaticas")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Lotes")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackendIntegrador.Domain.Entities.Ordeno", "Ordeno")
                        .WithMany("Lotes")
                        .HasForeignKey("OrdenoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Transporte", "Transporte")
                        .WithMany("Lotes")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CentroAcopio");

                    b.Navigation("Ordeno");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Lote", "Lote")
                        .WithMany("Muestras")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "TecnicoUsuario")
                        .WithMany("MuestrasComoTecnico")
                        .HasForeignKey("TecnicoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("TecnicoUsuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithMany("Ordenos")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.PrediccionGemelo", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithMany("PrediccionesGemelo")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Productores")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Productor")
                        .HasForeignKey("BackendIntegrador.Domain.Entities.Productor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.RecepcionAcopio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Recepciones")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Transporte", "Transporte")
                        .WithMany("Recepciones")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RecepcionesRegistradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroAcopio");

                    b.Navigation("Transporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ResultadoParametro", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.AnalisisCalidad", "Analisis")
                        .WithMany("Resultados")
                        .HasForeignKey("AnalisisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.ParametroCalidad", "Parametro")
                        .WithMany("Resultados")
                        .HasForeignKey("ParametroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analisis");

                    b.Navigation("Parametro");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Trabajador", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Trabajadores")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Trabajador")
                        .HasForeignKey("BackendIntegrador.Domain.Entities.Trabajador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Usuarios")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CentroAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Recepciones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.Navigation("AlertasGemelo");

                    b.Navigation("GemeloEstado");

                    b.Navigation("LecturasClimaticas");

                    b.Navigation("Ordenos");

                    b.Navigation("PrediccionesGemelo");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("CentrosAcopio");

                    b.Navigation("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ParametroCalidad", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.Navigation("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Productores");

                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Transporte", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MuestrasComoTecnico");

                    b.Navigation("Productor");

                    b.Navigation("RecepcionesRegistradas");

                    b.Navigation("Trabajador");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
