// <auto-generated />
using System;
using BackendIntegrador.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendIntegrador.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.Property<int>("AnalisisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraAnalisis")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuestraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasKey("AnalisisId");

                    b.HasIndex("MuestraId");

                    b.ToTable("AnalisisCalidad");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.Property<int>("CentroAcopioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CentroAcopioId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("CentrosAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.Property<int>("FincaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FincaId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ProductorId");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroAcopioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransporteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumenCapturadoLitros")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("LoteId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("OrdenoId");

                    b.HasIndex("TransporteId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.Property<int>("MuestraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraToma")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TecnicoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MuestraId");

                    b.HasIndex("LoteId");

                    b.HasIndex("TecnicoPorUsuarioId");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("MunicipioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.Property<int>("OrdenoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("FincaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumenLitros")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenoId");

                    b.HasIndex("FincaId");

                    b.ToTable("Ordenos");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ParametroCalidad", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("ParametroId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ParametrosCalidad");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.Property<int>("ProductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductorId");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Productores");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.RecepcionAcopio", b =>
                {
                    b.Property<int>("RecepcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroAcopioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemperaturaRecepcion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransporteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumenLitrosRecibidos")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("RecepcionId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("TransporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecepcionesAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ResultadoParametro", b =>
                {
                    b.Property<int>("AnalisisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParametroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorResultado")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("AnalisisId", "ParametroId");

                    b.HasIndex("ParametroId");

                    b.ToTable("ResultadosParametro");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("TipoDocumentoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaHoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemperaturaInicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransporteId");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CentroAcopioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CentroAcopioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Muestra", "Muestra")
                        .WithMany("Analisis")
                        .HasForeignKey("MuestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Municipio", "Municipio")
                        .WithMany("CentrosAcopio")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Fincas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Productor", "Productor")
                        .WithMany("Fincas")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("Productor");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Lotes")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Ordeno", "Ordeno")
                        .WithMany("Lotes")
                        .HasForeignKey("OrdenoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Transporte", "Transporte")
                        .WithMany("Lotes")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CentroAcopio");

                    b.Navigation("Ordeno");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Lote", "Lote")
                        .WithMany("Muestras")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "TecnicoUsuario")
                        .WithMany("MuestrasComoTecnico")
                        .HasForeignKey("TecnicoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("TecnicoUsuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Finca", "Finca")
                        .WithMany("Ordenos")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Productores")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Productor")
                        .HasForeignKey("BackendIntegrador.Domain.Entities.Productor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.RecepcionAcopio", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Recepciones")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Transporte", "Transporte")
                        .WithMany("Recepciones")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RecepcionesRegistradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroAcopio");

                    b.Navigation("Transporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ResultadoParametro", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.AnalisisCalidad", "Analisis")
                        .WithMany("Resultados")
                        .HasForeignKey("AnalisisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.ParametroCalidad", "Parametro")
                        .WithMany("Resultados")
                        .HasForeignKey("ParametroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analisis");

                    b.Navigation("Parametro");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.CentroAcopio", "CentroAcopio")
                        .WithMany("Usuarios")
                        .HasForeignKey("CentroAcopioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CentroAcopio");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("BackendIntegrador.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendIntegrador.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.AnalisisCalidad", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.CentroAcopio", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Recepciones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Finca", b =>
                {
                    b.Navigation("Ordenos");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Muestra", b =>
                {
                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("CentrosAcopio");

                    b.Navigation("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Ordeno", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.ParametroCalidad", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Productor", b =>
                {
                    b.Navigation("Fincas");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Productores");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Transporte", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("BackendIntegrador.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MuestrasComoTecnico");

                    b.Navigation("Productor");

                    b.Navigation("RecepcionesRegistradas");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
